Allow external configuration by config-file argument
sicpa-dlab/acapy-resolver-didcomm pull request #27
Opened 2021-06-10 11:08 UTC by Luis-GA

Signed-off-by: Luis Gomez <luis.gomezalonso@sicpa.com>

2021-06-11 11:45 UTC, Luis-GA commented
pending to fix

2021-06-14 14:38 UTC, dbluhm commented
We briefly discussed this on our stand up call already but to just put it in writing: the mock resolver config was loaded separately from the usual docker config. Since we changed our plugin configuration loading strategy, that config was no longer getting pulled in.

2021-06-15 14:00 UTC, dbluhm requested changes

2021-06-15 14:50 UTC, Luis-GA commented on docker/default.yml
> +
This argument is useless right now, I have pruned all the plugin-config in the #29

2021-06-15 16:58 UTC, dbluhm approved these changes

2021-06-15 16:58 UTC, merged